server:
  port: 9090
  servlet:
    context-path: /interview-agent
    encoding:
      charset: UTF-8
      force: true

spring:
  mvc:
    contentnegotiation:
      default-content-type: application/json
  application:
    name: ai-interview-coach-backend
  profiles:
    active: dev
  cache:
    type: caffeine
    # 【核心修正】在 cache-names 列表中，加入我们新的缓存空间
    cache-names:
      - questionsByTag          # 用于“按标签筛选”接口的缓存
      - questionSearchResults   # 【新增】用于统一搜索接口的缓存
    caffeine:
      spec: > # 这个配置会应用到上面列表中的所有缓存
        maximumSize=1000,
        expireAfterWrite=10m

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 105MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true

management:
  health:
    db:
      enabled: false # 禁用默认的数据源健康检查
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always # ? when_authorized

logging:
  level:
    root: INFO
    com:
      czdxwx:
        aiinterviewcoachbackend: DEBUG
  file:
    name: logs/ai-coach-backend.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

app:
  jwt:
    secret: "Ar8l7Jr1RjCIw+BXT6OpOyG4Aso301GtojyZfL9urgHLm3D/uQiCqaR1cHECg4a201bkhm49vboFFt+IMA+OpQ=="
    expiration-ms: 3600000
    # refreshExpirationMs: 604800000
    header: "Authorization"
    tokenPrefix: "Bearer"

spark:
  # 用于生成题目的聊天与Function Calling服务

  embedding:
    appid: d6422ddf
    apikey: e235e3a86546316eab30a8398b764260
    apisecret: NmIwZmM0ZTJlMWQ3MjQ4NWIxY2YzM2M2
    url: https://emb-cn-huabei-1.xf-yun.com/

  # 用于文本向量化的服务
  chat:
    appid: 318bbfa3
    apikey: fa7392d3ee2c7c8c12bbb10f5b47659f
    apisecret: OGE5NmU0Yzg1OWY4NmE5ZTZkYWM3ODE0
    url: https://spark-api.xf-yun.com/v4.0/chat

  tts:
    url: https://tts-api.xfyun.cn/v2/tts # 使用新的 v2 接口地址
    appid: d6422ddf   # 填入您用于语音合成的 AppID
    apikey: e235e3a86546316eab30a8398b764260   # 填入您用于语音合成的 APIKey
    apisecret: NmIwZmM0ZTJlMWQ3MjQ4NWIxY2YzM2M2 # 填入您用于语音合成的 APISecret
    default-voice-name: x4_xiaoyan
milvus:
  host: in03-3a34be53b23c3be.serverless.gcp-us-west1.cloud.zilliz.com
  token: 992b27b22b7c2360230aef06a89e647730868eac17f941fdc4af5874da35f9e2e10ea7581198c5e17b057b3e3fc7511906419700
  collection:
    questions: interview_questions
    tags: interview_tags
    dimension: 2560