#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: "jstbb520"
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://localhost:3306/aicoach_db_dev?useSSL=false&useUnicode=true&characterEncoding=utf8
#    username: root

spring:
  # 数据源配置
  datasource:
    # 【重要】指定连接池类型为 Druid
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aicoach_db_dev?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: "jstbb520"
    # Druid 特定配置
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/* # 访问路径，例如 http://localhost:8080/druid
        login-username: admin # 监控页面的登录用户名
        login-password: admin # 监控页面的登录密码
        allow: # 白名单，为空或不配置则允许所有访问
        deny: # 黑名单
      # 开启Web应用的SQL监控
      web-stat-filter:
        enabled: true
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
# ===================================================================
# MyBatis-Plus 配置
# ===================================================================
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml # XML映射文件位置 (如果使用XML)
  type-aliases-package: com.czdxwx.aiinterviewcoachbackend.entity # 实体类别名包路径 (替换为您的包名)
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开发时打印SQL到控制台
  global-config:
    db-config:
      id-type: auto # ID自增策略 (或 assign_id, assign_uuid 等)
      # table-prefix: tbl_ # 如果表有统一前缀
      # logic-delete-field: deleted # 逻辑删除字段 (实体类中需要有对应字段和注解)
      # logic-delete-value: 1 # 逻辑删除值 (标记为已删除)
      # logic-not-delete-value: 0 # 逻辑未删除值
# 自定义应用属性
app:
  file-storage:
    # 在 Windows 开发环境下，相对路径会解析到项目根目录
    # 例如：D:/projects/ai-interview-coach-backend/uploads/resumes
    upload-dir: uploads